config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end


  # root to: 'pages#welcome'
  # get 'home', to: 'pages#home'
  # get 'press', to: 'pages#press'
  # get 'contacto', to: 'pages#contacto'
  # get 'playlist', to: 'pages#playlist'
  # resources :artworks
  # resources :shows
  # resources :staffs
  # resources :carnivals

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artists
  # has_many :artworks

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  private

  def set_artists
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.erb
<div class="py-3 pt-8" style="padding-left: 92%;">
  <div class="py-1 px-2 btn flex flex-row-reverse items-center">
    <div><%= image_tag asset_path('yellowCircle.png')%></div>
    <h1 class="text-right font-extralight pr-3 pl-1">LISTA</h1>
  </div>
</div>

<div class="flex flex-wrap justify-between">
  <% @artists.each do |artist|  %>
  <div class="randomize" style="max-height: 28%;  max-width: 28%; padding-bottom: 1%;">
    <p class="uppercase text-2xl font-light py-10"><%= link_to "#{artist.name}", artist_path(artist)  %></p>
    <div><%= image_tag "#{artist.about}" %></div>
  </div>
  <% end %>
</div>


<div class="py-3 pt-8" style="padding-left: 91%;">
  <div class="py-1 px-2 btn flex flex-row-reverse items-center">
    <div><%= image_tag asset_path('yellowCircle.png')%></div>
    <h1 class="text-right font-extralight pr-3 pl-1">GRILLA</h1>
  </div>
</div>


<div class="flex items-center">

<!--   <div class="w-2/3"> -->
    <div class="flex flex-wrap justify-between mr-12">
      <% @artists.each do |artist|  %>
      <div class="randomize" style="max-height: 28%;  max-width: 28%; padding-bottom: 2%;">
        <p class="text-2xl font-light py-10 px-8"><%= link_to "#{artist.name}", artist_path(artist)  %></p>
      </div>
      <% end %>
    </div>
<!--   </div> -->

<!--   <div class="w-1/3">
        <div><%= image_tag asset_path('actual.png')%></div>
  </div> -->
</div>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maria Casado</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="/dist/output.css" rel="stylesheet">
<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

  </head>

  <body>

    <% if content_for? :menu %>
      <%= yield %>

    <% else %>
      <%= render 'shared/navbar' %>
      <%= yield %>
      <%= render 'shared/footer' %>

    <% end %>

  </body>

</html>

app/views/pages/home.html.erb
hello

app/views/shared/_footer.html.erb
<div class="text-sm text-gray-500 font-extralight" style="margin-top: auto;">
  <div class="bg-gray-100 flex justify-center items-center px-12 py-8">

    <div class="flex-1">
      <h1>INFO@MARIACASADO.COM.AR </h1>
      <h1>+5491154516796</h1>
    </div>

    <div class="flex-shrink-0 btn font-thin text-sm px-3 py-1 mx-2 btn-footer pr-6">
      <h1>inscribite para recibir nuestras novedades</h1>
    </div>

    <div class="flex-1">
      <div class="flex flex-row-reverse">
        <div class="px-2 py-2 btn-footer mr-2">
          <%= link_to href: 'https://www.instagram.com/mariacasado.homegallery/' do %>
          <%= image_tag 'instaFooter.png'%>
          <% end %>
        </div>
        <div class="px-2 py-2 btn-footer mr-2">
          <%= link_to href: 'https://www.facebook.com/mariacasadoHG/' do %>
          <%= image_tag 'fbFooter.png'%>
          <% end %>
        </div>

      </div>
    </div>

  </div>
</div>



<!-- <div class="bg-gray-100">
  <div class="py-16 px-16">
    <div class="flex">
      <div class="flex-grow">
        <h1>INFO@MARIACASADO.COM.AR </h1>
        <h1>+5491154516796</h1>
      </div class="flex-grow">
      <h1>inscribite para recibir nuestras novedades</h1>
      <div class="flex flex-grow">
        <h1>fb</h1>
        <h1>insta</h1>
      </div>
    </div>
  </div>
</div> -->

<!--
<div class="bg-blue-700 flex-grow-1" style=" min-height: 100vh; display: flex; flex-direction: column;">


  <div class="text-center text-2xl bg-white font-medium" style="margin-top: auto;">
    <div class="bg-blue-700 py-4">
      <h3 class="text-white">ROCAMORA 4343</h3>
      <h3 class="text-white">1425, BUENOS AIRES, ARGENTINA</h3>
    </div>
    <h1 class="py-2">INSTAGRAM, FACEBOOK, LINKEDIN</h1>
  </div>

</div>
-->


<!--
  <div class="bg-gray-100 flex subs justify-center items-center px-10 py-8">

    <div class="flex-1">
      <div class="mx-2 self-center">
        <h1>INFO@MARIACASADO.COM.AR </h1>
        <h1>+5491154516796</h1>
      </div>
    </div>

    <div class="flex-shrink-0">
      <h1>inscribite para recibir nuestras novedades</h1>
    </div>

    <div class="flex-1">
      <div class="flex flex-row-reverse">
        <h1>insta</h1>
        <h1>fb</h1>
      </div>
    </div>

  </div> -->

app/views/shared/_navbar.html.erb
<div class="navbar pt-3">
  <div class="logo-navbar pt-1 pb-2" style="height: 50px;">
    <%= image_tag asset_path('logo.png')%>
  </div>
  <div class="navbar-flex">
    <h1 class="navbar-link font-extralight"><%= link_to "artistas", artists_path %></h1>
    <h1 class="navbar-link font-extralight"><%= link_to "nosotros", artists_path %></h1>
    <h1 class="navbar-link font-extralight"><%= link_to "muestras", artists_path %></h1>
    <h1 class="navbar-link font-extralight"><%= link_to "ferias", artists_path %></h1>
    <h1 class="navbar-link font-extralight"><%= link_to "random", artists_path %></h1>
    <h1 class="navbar-link font-extralight"><%= link_to "playlist", artists_path %></h1>
    <h1 class="navbar-link font-extralight"><%= link_to "contacto", artists_path %></h1>
  </div>
</div>

      <!--button class="navbar-toggler btn-menu" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </!--button-->